server:
  port: 8761

eureka:
  client:
    #False values used to run one eureka instance(just for testing and demo)
    registerWithEureka: false
    fetchRegistry: false

    eurekaServerURLContext: eureka
    #serviceUrl:
    #  defaultZone: http://server1-url/eureka/,http://server2-url/eureka/
